# We use the internal DNS server of Docker, which is available at 127.0.0.11
# Why? Because it allows us to resolve service names defined in the Docker Compose file,
# which is essential for most setups.
resolver 127.0.0.11 valid=30s;
resolver_timeout 5s;
