name: PHP 7.4
on:
  push:
    branches: [ "main" ]
    paths:
      - src/php/7.4/**
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push fpm-alpine
        run: bin/build.sh php 7.4 fpm-alpine --push
